# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  test:
    docker:
      - image: "swift:<< matrix.version >>"

    steps:
      - checkout
      - run: make test_all

workflows:
  workflow:
    jobs:
      - test:
        matrix:
          parameters:
            version: ["5.0-bionic", "5.1-bionic", "5.2-bionic"]
