# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  workflow:
    jobs:
      - build:
        matrix:
          parameters:
            docker_image: ["5.0-bionic", "5.1-bionic", "5.2-bionic"]
        docker:
          - image: "swift:<< matrix.version >>"

        steps:
          - checkout
          - run: make test_all
